ft(user-registration):users should be register.
andela/ah-frontend-prime pull request #14
Opened 2019-05-09 05:01 UTC by anyatibrian

### What does this PR do?

- Creates functionality that enable user to register and activate their account

Description of tasks to be completed.

- Add user registration functionality
- Add registration functionality tests
- Add registration modal which takes inputs
- Add error and success messages when register userin

How should this be manually tested?

- Click the register  button redirects you to the login page  after entering  the details

Any background context you want to provide?

- N/A

What are the relevant pivotal tracker stories?

[#164798250](https://www.pivotaltracker.com/story/show/164798250)

Screenshots(if appropriate)

2019-05-09 11:34 UTC, e-ian approved these changes
Tested. Good work with frontend validations @anyatibrian. LGTM.

2019-05-09 12:58 UTC, e-ian reviewed
@anyatibrian please ensure the branch is deployed to heroku

2019-05-09 14:24 UTC, patrickf949 approved these changes
Tested. LGTM

2019-05-09 20:58 UTC, MuhanguziDavid commented on src/tests/components/registerComponent.test.js
> +  it("should simulate have been clicked", () => {
have more descriptive test names

2019-05-09 20:59 UTC, MuhanguziDavid commented on src/tests/components/registerComponent.test.js
> +    onSubmit.find(".button-success").simulate("click");
Every test should have an expectation or assertion (this applies for every other test without an `except` statement

2019-05-09 21:05 UTC, MuhanguziDavid requested changes
Nice work @anyatibrian , please
- correct your PR title
- have a descriptive PR description especially `How to test this PR`
- improve the warning message `wrong password must at least one number, lowercase char,special char` when someone enters a password that does not fulfil criteria.
- ensure that error toasts are red
- error toast shouldn’t be timed, a user should see the error and close it themselves.
- Add a loader
- redirect a user to either the login page or the home page after registration.
- fix all eslint issues
- add a screenshot(s) to your Pr description. 
- work on coverage, it could be better than that

2019-05-11 21:43 UTC, MuhanguziDavid requested changes
- The login functionality seems to have been broken. It returns an error!?
- Ensure that the register page is responsive
- I see two toasts per action. Ensure to have only one
- Error toasts should not be timed. Just add a statement to remove previous toasts when a new action is performed (@e-ian did it on his task, he could help out).
- ensure that your registration form fulfils the requirements given by the PO e.g. remove the word "enter" from the titles, etc
- punctuate the message on successful registration. It is a bit confusing without punctuation.

2019-05-14 07:03 UTC, anyatibrian commented
> Nice work @anyatibrian , please
> 
> * correct your PR title
> * have a descriptive PR description especially `How to test this PR`
> * improve the warning message `wrong password must at least one number, lowercase char,special char` when someone enters a password that does not fulfil criteria.
> * ensure that error toasts are red
> * error toast shouldn’t be timed, a user should see the error and close it themselves.
> * Add a loader
> * redirect a user to either the login page or the home page after registration.
> * fix all eslint issues
> * add a screenshot(s) to your Pr description.
> * work on coverage, it could be better than that

done

2019-05-14 07:04 UTC, anyatibrian commented
> * The login functionality seems to have been broken. It returns an error!?
> * Ensure that the register page is responsive
> * I see two toasts per action. Ensure to have only one
> * Error toasts should not be timed. Just add a statement to remove previous toasts when a new action is performed (@e-ian did it on his task, he could help out).
> * ensure that your registration form fulfils the requirements given by the PO e.g. remove the word "enter" from the titles, etc
> * punctuate the message on successful registration. It is a bit confusing without punctuation.

all done

2019-05-14 07:04 UTC, anyatibrian commented
> * The login functionality seems to have been broken. It returns an error!?
> * Ensure that the register page is responsive
> * I see two toasts per action. Ensure to have only one
> * Error toasts should not be timed. Just add a statement to remove previous toasts when a new action is performed (@e-ian did it on his task, he could help out).
> * ensure that your registration form fulfils the requirements given by the PO e.g. remove the word "enter" from the titles, etc
> * punctuate the message on successful registration. It is a bit confusing without punctuation.

all done

2019-05-14 07:13 UTC, Genza999 approved these changes
Great work @anyatibrian . Kindly fix the spelling error in the 3rd commit message i.e registration and also make the _finishes_ statement start with a capital F.

2019-05-14 08:00 UTC, merged